Mapowanie ulic
openstreetmap-polska/gugik2osm pull request #113
Opened 2022-09-03 14:51 UTC by mskakuj

2022-09-13 20:30 UTC, ttomasz requested changes
w jednej nazwie została kropka

2022-09-13 20:30 UTC, ttomasz commented on processing/sql/data/street_names_mappings.csv
> +0107821,59762,płk. Piotra Bartaka,Pułkownika. Piotra Bartaka
kropka się ostała :)

2022-09-14 18:04 UTC, mskakuj commented on processing/sql/data/street_names_mappings.csv
> +0107821,59762,płk. Piotra Bartaka,Pułkownika. Piotra Bartaka
skorygowane

2022-09-14 21:54 UTC, ttomasz approved these changes

2022-09-14 21:54 UTC, merged